/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OneoneRouteImport } from './routes/oneone'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as CloszrEmbedRouteImport } from './routes/closzr-embed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCloszrRouteImport } from './routes/api/closzr'

const OneoneRoute = OneoneRouteImport.update({
  id: '/oneone',
  path: '/oneone',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const CloszrEmbedRoute = CloszrEmbedRouteImport.update({
  id: '/closzr-embed',
  path: '/closzr-embed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloszrRoute = ApiCloszrRouteImport.update({
  id: '/api/closzr',
  path: '/api/closzr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/closzr-embed': typeof CloszrEmbedRoute
  '/forecast': typeof ForecastRoute
  '/oneone': typeof OneoneRoute
  '/api/closzr': typeof ApiCloszrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/closzr-embed': typeof CloszrEmbedRoute
  '/forecast': typeof ForecastRoute
  '/oneone': typeof OneoneRoute
  '/api/closzr': typeof ApiCloszrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/closzr-embed': typeof CloszrEmbedRoute
  '/forecast': typeof ForecastRoute
  '/oneone': typeof OneoneRoute
  '/api/closzr': typeof ApiCloszrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/closzr-embed'
    | '/forecast'
    | '/oneone'
    | '/api/closzr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/closzr-embed'
    | '/forecast'
    | '/oneone'
    | '/api/closzr'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/closzr-embed'
    | '/forecast'
    | '/oneone'
    | '/api/closzr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CloszrEmbedRoute: typeof CloszrEmbedRoute
  ForecastRoute: typeof ForecastRoute
  OneoneRoute: typeof OneoneRoute
  ApiCloszrRoute: typeof ApiCloszrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oneone': {
      id: '/oneone'
      path: '/oneone'
      fullPath: '/oneone'
      preLoaderRoute: typeof OneoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closzr-embed': {
      id: '/closzr-embed'
      path: '/closzr-embed'
      fullPath: '/closzr-embed'
      preLoaderRoute: typeof CloszrEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/closzr': {
      id: '/api/closzr'
      path: '/api/closzr'
      fullPath: '/api/closzr'
      preLoaderRoute: typeof ApiCloszrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CloszrEmbedRoute: CloszrEmbedRoute,
  ForecastRoute: ForecastRoute,
  OneoneRoute: OneoneRoute,
  ApiCloszrRoute: ApiCloszrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
