-- Trigger: dispatch front_forecast.yml when a snapshot is created
-- without close_probability (i.e. freshly generated by front_deals).

CREATE OR REPLACE FUNCTION dispatch_front_forecast()
RETURNS TRIGGER AS $$
DECLARE
    _pat  TEXT;
    _repo TEXT;
BEGIN
    IF NEW.close_probability IS NOT NULL THEN
        RETURN NEW;
    END IF;

    SELECT decrypted_secret INTO _pat
    FROM vault.decrypted_secrets
    WHERE name = 'github_pat';

    IF _pat IS NULL THEN
        RAISE WARNING 'github_pat not found in vault';
        RETURN NEW;
    END IF;

    _repo := current_setting('app.settings.github_repo', true);
    IF _repo IS NULL OR _repo = '' THEN
        _repo := 'guillemcatalan/claudio';
    END IF;

    PERFORM net.http_post(
        url     := 'https://api.github.com/repos/' || _repo || '/actions/workflows/front_forecast.yml/dispatches',
        headers := jsonb_build_object(
            'Authorization', 'Bearer ' || _pat,
            'Accept', 'application/vnd.github+json'
        ),
        body    := jsonb_build_object(
            'ref', 'main',
            'inputs', jsonb_build_object('snapshot_id', NEW.id::text)
        )
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_front_deal_forecast
    AFTER INSERT OR UPDATE ON front_deal_snapshots
    FOR EACH ROW
    WHEN (NEW.close_probability IS NULL)
    EXECUTE FUNCTION dispatch_front_forecast();
