-- ============================================================================
-- Migration 029: PBD Snapshots table
-- ============================================================================
-- Stores BANT qualification snapshots for deals in PBD stages.
-- Generated by Claude when deal_confirmations.all_ready = TRUE and the deal
-- is in a PBD stage. Stops generating when deal exits Demo Booked.
-- ============================================================================

CREATE TABLE pbd_snapshots (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    deal_id         UUID REFERENCES deals(id) ON DELETE CASCADE,
    hs_deal_id      TEXT NOT NULL,
    snapshot_date   DATE NOT NULL,

    bant_b_status   TEXT,
    bant_b_evidence TEXT,
    bant_a_status   TEXT,
    bant_a_evidence TEXT,
    bant_n_status   TEXT,
    bant_n_evidence TEXT,
    bant_t_status   TEXT,
    bant_t_evidence TEXT,

    pbd             TEXT,
    pbd_summary     TEXT,

    created_at TIMESTAMPTZ DEFAULT now(),

    UNIQUE(hs_deal_id, snapshot_date)
);

CREATE INDEX idx_pbd_snapshots_deal_id ON pbd_snapshots(deal_id);
CREATE INDEX idx_pbd_snapshots_hs_deal_id ON pbd_snapshots(hs_deal_id);

ALTER TABLE pbd_snapshots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anon read" ON pbd_snapshots FOR SELECT TO anon USING (true);
CREATE POLICY "Authenticated read" ON pbd_snapshots FOR SELECT TO authenticated USING (true);
CREATE POLICY "Service write" ON pbd_snapshots FOR ALL TO service_role USING (true);
